#include "server_constant.h"

float MAP_LIMIT_X = 640;
float MAP_LIMIT_Y = 480;

// duck editor
float POSICION_INICIAL_X = 0;
float POSICION_INICIAL_Y = 0;
int LIFE = 100;
float GRAVEDAD = 1;
float VELOCIDAD_INICIAL = 15;

float RANGO_X_MEDIO = 4;
float RANGO_X_CORTO = 4;
float RANGO_X_LARGO = 12;
// GRANADA
float VELOCIDAD_GRANADA = 20;
int GRANADA_TIME_TO_EXPLODE = 246;
uint8_t COUNTER_TO_SHOOT_GRANADA = 1;

// GRANADA
int DAMAGE_GRANADA = 10;
int RANGE_GRANADA = 38;
int AMMO_GRANADA = 100;
float RECOIL_GRANADA = 0;
float RADIO_EXPLOTION_GRANADA = 2;
// BANANA
int DAMAGE_BANANA = 10;
int RANGE_BANANA = 10;
int AMMO_BANANA = 3;
float RECOIL_BANANA = 0;
// AK47
int DAMAGE_AK47 = 10;
int RANGE_AK47 = 13;
int AMMO_AK47 = 100;
float RECOIL_AK47 = 1;
// LASER RIFLE
int DAMAGE_LASER_RIFLE = 10;
int RANGE_LASER_RIFLE = 30;
int AMMO_LASER_RIFLE = 100;
float RECOIL_LASER_RIFLE = 0;
// PEW PEW LASER
int DAMAGE_PEW_PEW_LASER = 10;
int RANGE_PEW_PEW_LASER = 38;
int AMMO_PEW_PEW_LASER = 120;
float RECOIL_PEW_PEW_LASER = 0;
// ESCOPETA
int DAMAGE_ESCOPETA = 10;
int RANGE_ESCOPETA = 9;
int AMMO_ESCOPETA = 200;
float RECOIL_ESCOPETA = 0;
// SNIPER
int DAMAGE_SNIPER = 10;
int RANGE_SNIPER = 64;
int AMMO_SNIPER = 100;
float RECOIL_SNIPER = 0;
// COWBOY
int DAMAGE_COWBOY = 10;
int RANGE_COWBOY = 20;
int AMMO_COWBOY = 100;
float RECOIL_COWBOY = 0;
// PISTOLA DUELOS
int DAMAGE_PISTOLA_DUELOS = 10;
int RANGE_PISTOLA_DUELOS = 5;
int AMMO_PISTOLA_DUELOS = 100;
float RECOIL_PISTOLA_DUELOS = 0;
// MAGNUM
int DAMAGE_MAGNUM = 10;
int RANGE_MAGNUM = 20;
int AMMO_MAGNUM = 100;
float RECOIL_MAGNUM = 2;

float COWBOY_SPREAD = 0;
float AK47_SPREAD_INITIAL = 0;
float PISTOLA_DUELOS_SPREAD = 0.3;
float MAGNUM_SPREAD = 0.3;
float ESCOPETA_MAX_SPREAD = 1;
float SNIPER_SPREAD = 0;
float GRANADA_SPREAD = 0.3;
float BANANA_SPREAD = 0.3;
float PEW_PEW_LASER_MAX_SPREAD = 0.3;
float LASER_RIFLE_SPREAD = 3;

// partidas
uint8_t NECESARY_VICTORY_ROUNDS = 10;
uint8_t GAMES_PER_ROUND = 5;
