#ifndef TALLER_TP_CONSTANTTEXTURES_H
#define TALLER_TP_CONSTANTTEXTURES_H

#define IMAGE_ARMOR DATA_PATH "/armour/pechera.png"
#define IMAGE_BOX_WEAPON DATA_PATH "/objects/itemBox.png"
#define IMAGE_GRANADA_EXPLOTION DATA_PATH "/bullets/explode.png"
#define IMAGE_AMMO_1 DATA_PATH "/bullets/ammo.png"
#define IMAGE_AMMO_2 DATA_PATH "/bullets/ammo2.png"
#define IMAGE_AMMO_3 DATA_PATH "/bullets/ammo3.png"
#define IMAGE_AMMO_4 DATA_PATH "/bullets/ammo4.png"
#define IMAGE_AMMO_5 DATA_PATH "/bullets/ammo5.png"
#define IMAGE_LASER_AMMO DATA_PATH "/bullets/laserAmmo.png"
#define IMAGE_LASER_AMMO2 DATA_PATH "/bullets/laserAmmo2.png"
#define IMAGE_GRANADA_BULLET DATA_PATH "/bullets/thrownGrenade.png"
#define IMAGE_GRANADA_EXPLOTION DATA_PATH "/bullets/explode.png"
#define IMAGE_BANANA_BULLET DATA_PATH "/bullets/banana.png"
#define IMAGE_BANANA_THROWN DATA_PATH "/bullets/thrownBanana.png"
#define IMAGE_DUCK DATA_PATH "/objects/Duck.png"
#define IMAGE_COWBOY_GUN DATA_PATH "/weapons/cowboyPistol.png"
#define IMAGE_COWBOY_GUN_EQUIPPED DATA_PATH "/weapons/CowboyPistolEquipped.png"
#define IMAGE_AK47_GUN DATA_PATH "/weapons/ak47.png"
#define IMAGE_AK47_GUN_EQUIPPED DATA_PATH "/weapons/ak47Equipped.png"
#define IMAGE_PISTOLA_DUELOS_GUN DATA_PATH "/weapons/duelingPistol.png"
#define IMAGE_PISTOLA_DUELOS_GUN_EQUIPPED                                      \
  DATA_PATH "/weapons/duelingPistolEquipped.png"
#define IMAGE_MAGNUM_GUN DATA_PATH "/weapons/magnum.png"
#define IMAGE_MAGNUM_GUN_EQUIPPED DATA_PATH "/weapons/magnumEquipped.png"
#define IMAGE_ESCOPETA_GUN DATA_PATH "/weapons/shotgun.png"
#define IMAGE_ESCOPETA_GUN_EQUIPPED DATA_PATH "/weapons/shotgunEquipped.png"
#define IMAGE_SNIPER_GUN DATA_PATH "/weapons/sniper.png"
#define IMAGE_SNIPER_GUN_EQUIPPED DATA_PATH "/weapons/sniperEquipped.png"
#define IMAGE_GRANADA_GUN DATA_PATH "/weapons/grenade.png"
#define IMAGE_GRANADA_GUN_EQUIPPED DATA_PATH "/weapons/grenadeEquipped.png"
#define IMAGE_BANANA_GUN DATA_PATH "/weapons/bananaSpawn.png"
#define IMAGE_BANANA_GUN_EQUIPPED DATA_PATH "/weapons/bananaEquipped.png"
#define IMAGE_PEW_PEW_LASER_GUN DATA_PATH "/weapons/PewpewLaser.png"
#define IMAGE_PEW_PEW_LASER_GUN_EQUIPPED                                       \
  DATA_PATH "/weapons/PewpewLaserEquipped.png"
#define IMAGE_LASER_RIFLE_GUN DATA_PATH "/weapons/laserRifle.png"
#define IMAGE_LASER_RIFLE_GUN_EQUIPPED                                         \
  DATA_PATH "/weapons/laserRifleEquipped.png"
#define IMAGE_HELMET DATA_PATH "/armour/casco.png"
#define IMAGE_PLATAFORMA_DONUT DATA_PATH "/platforms/Donut.png"
#define IMAGE_PLATAFORMA_DONUT_LONG DATA_PATH "/platforms/Donut long.png"
#define IMAGE_PLATAFORMA_INDUSTRIAL DATA_PATH "/platforms/Industrial.png"
#define IMAGE_PLATAFORMA_NATURE DATA_PATH "/platforms/Nature.png"
#define IMAGE_PLATAFORMA_NATURE_LONG DATA_PATH "/platforms/Nature long.png"
#define IMAGE_PLATAFORMA_SPACE DATA_PATH "/platforms/Space.png"
#define IMAGE_PLATAFORMA_UNDERGROUND DATA_PATH "/platforms/Underground.png"
#define IMAGE_WALL_DONUT DATA_PATH "/walls/Donut.png"
#define IMAGE_WALL_NATURE DATA_PATH "/walls/Nature.png"
#define IMAGE_WALL_UNDERGROUND DATA_PATH "/walls/Underground.png"


#endif //TALLER_TP_CONSTANTTEXTURES_H
