
life: 100
granade:
  damage: 50
  range: 5
  ammo: 1
  recoil: 0.5

banana:
    damage: 30
    range: 5
    ammo: 1
    recoil: 0.5

ak47:
    damage: 20
    range: 5
    ammo: 100
    recoil: 0.5

laser_rifle:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

pew_pew_laser:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

escopeta:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

sniper:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

cowboy:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

pistola_de_duelos:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5

magnum:
    damage: 20
    range: 5
    ammo: 30
    recoil: 0.5


