necesary_victories: 10
games_per_round: 5

life: 100
jump_velocity: 15
gravity: 1

granade:
  damage: 50
  range: 5
  ammo: 1
  recoil: 0
  radius_explosion: 3

banana:
    damage: 0
    range: 5
    ammo: 1
    recoil: 0

ak47:
    damage: 8
    range: 13
    ammo: 30
    recoil: 1
    spread_initial: 0

laser_rifle:
    damage: 20
    range: 30
    ammo: 10
    recoil: 0
    spread: 3

pew_pew_laser:
    damage: 12
    range: 38
    ammo: 12
    recoil: 0
    max_spread: 0.3

escopeta:
    damage: 10
    range: 5
    ammo: 30
    recoil: 0
    max_spread: 1

sniper:
    damage: 80
    range: 5
    ammo: 30
    recoil: 0

cowboy:
    damage: 15
    range: 20
    ammo: 6
    recoil: 0

pistola_de_duelos:
    damage: 50
    range: 5
    ammo: 1
    recoil: 0
    spread: 0.3

magnum:
    damage: 25
    range: 20
    ammo: 6
    recoil: 0.5
    spread: 0.3


