#include "server_constant.h"

float MAP_LIMIT_X = 640;
float MAP_LIMIT_Y = 480;
uint8_t SCENE_ID = 0x02;

float GRAVEDAD = 1;
float VELOCIDAD_INICIAL = 15;
float GRAVITY_FLAP = 0.001;
uint8_t CANT_FLAP = 100;

// duck editor
float POSICION_INICIAL_X = 0;
float POSICION_INICIAL_Y = 0;
uint8_t LIFE = 100;

float RANGO_X_MEDIO = 4;
float RANGO_X_CORTO = 4;
float RANGO_X_LARGO = 12;
// GRANADA
float VELOCIDAD_GRANADA = 20;
uint8_t GRANADA_TIME_TO_EXPLODE = 246;
uint8_t COUNTER_TO_SHOOT_GRANADA = 1;

// GRANADA
uint8_t DAMAGE_GRANADA = 10;
uint8_t RANGE_GRANADA = 38;
int AMMO_GRANADA = 100;
float RECOIL_GRANADA = 0;
// BANANA
uint8_t DAMAGE_BANANA = 10;
uint8_t RANGE_BANANA = 10;
int AMMO_BANANA = 100;
float RECOIL_BANANA = 0;
// AK47
uint8_t DAMAGE_AK47 = 10;
uint8_t RANGE_AK47 = 13;
int AMMO_AK47 = 100;
float RECOIL_AK47 = 1;
// LASER RIFLE
uint8_t DAMAGE_LASER_RIFLE = 10;
uint8_t RANGE_LASER_RIFLE = 30;
int AMMO_LASER_RIFLE = 100;
float RECOIL_LASER_RIFLE = 0;
// PEW PEW LASER
uint8_t DAMAGE_PEW_PEW_LASER = 10;
uint8_t RANGE_PEW_PEW_LASER = 38;
int AMMO_PEW_PEW_LASER = 120;
float RECOIL_PEW_PEW_LASER = 0;
// ESCOPETA
uint8_t DAMAGE_ESCOPETA = 10;
uint8_t RANGE_ESCOPETA = 9;
int AMMO_ESCOPETA = 200;
float RECOIL_ESCOPETA = 0;
// SNIPER
uint8_t DAMAGE_SNIPER = 10;
uint8_t RANGE_SNIPER = 64;
int AMMO_SNIPER = 100;
float RECOIL_SNIPER = 0;
// COWBOY
uint8_t DAMAGE_COWBOY = 10;
uint8_t RANGE_COWBOY = 20;
int AMMO_COWBOY = 100;
float RECOIL_COWBOY = 0;
// PISTOLA DUELOS
uint8_t DAMAGE_PISTOLA_DUELOS = 10;
uint8_t RANGE_PISTOLA_DUELOS = 5;
int AMMO_PISTOLA_DUELOS = 100;
float RECOIL_PISTOLA_DUELOS = 0;
// MAGNUM
uint8_t DAMAGE_MAGNUM = 10;
uint8_t RANGE_MAGNUM = 20;
int AMMO_MAGNUM = 100;
float RECOIL_MAGNUM = 2;
